version: "3.7"

services:
  app:
    build:
      context: .
      target: dev
    user: "${UID}:${GID}"
    volumes:
      - ./src:/src:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:8.0.28-debian
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  db:
